modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_clockwork"
version = "${version}"
displayName = "Create Clockwork Mod"
authors = ["fluffy", "potato", "ewoudje"]
description = '''

'''
logoFile = "icon.png"

[[dependencies.vs_clockwork]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_clockwork]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_clockwork]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_clockwork]]
modId = "create"
mandatory = true
versionRange="${create_version}"
ordering = "NONE"
side = "BOTH"